### hello requestParam
GET {{base-url}}/hello?name=

### hello pathVariable
GET {{base-url}}/hello/james

### hello requestBody
POST {{base-url}}/hello
content-type: application/json

{
  "name": ""
}
