language: java
jdk:
  - openjdk11

branches:
  - chmod +x gradlew

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: './gradlew clean build'

notifications:
  email:
    recipients:
      - hangjastar@gmail.com