name: approve

on:
  workflow_dispatch

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: echo hello world
        run: echo hello-world
  approve:
    runs-on: ubuntu-latest
    environment: approval
    needs: [hello-world]
    steps:
      - name: approve
        run: |
          echo "approve done"
