name: context
on: workflow_dispatch

jobs:
  context:
    runs-on: ubuntu-latest
    steps:
      - name: echo github context
        run: echo '${{ toJson(github) }}'
      - name: check github context
        run: |
          echo ${{ github.repository }}
          echo ${{ github.event_name }}
          echo ${{ github.repository_owner }}
