name: environment v2
on:
  workflow_dispatch

jobs:
  get-var:
    runs-on: ubuntu-latest
    environment: develop
    steps:
      - name: get var
        run: |
          echo ${{ vars.name }}
          echo ${{ vars.secret_key }}
