name: using set environment module
on:
  push:
  workflow_dispatch:

jobs:
  using-module:
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.set-env.outputs.environment }}
    steps:
      - name: fetch action repo
        uses: actions/checkout@v4
        with:
          repository: "bekurin/github-actions-module-in-action"
          path: "./github-actions"
      - name: use set-environment module
        uses: ./github-actions/set-environment
        id: set-env
        with:
          REF_TYPE: ${{ github.ref_type }}
          BASE_REF: ${{ github.base_ref }}
  using-environment:
    runs-on: ubuntu-latest
    needs: [using-module]
    strategy:
      matrix:
        environment: ["${{ needs.set-environment-outputs.environment }}"]
    environment: ${{ matrix.environment }}
