# Generated by Django 3.2.5 on 2021-08-12 14:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import righteous.db.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=100, unique=True)),
                ('eng_name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(max_length=255, upload_to=righteous.db.utils.get_directory_path)),
                ('is_available', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, unique=True)),
                ('eng_name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('description', models.TextField(blank=True, max_length=300)),
                ('price', models.PositiveIntegerField()),
                ('stock', models.IntegerField()),
                ('images', models.ImageField(max_length=255, upload_to=righteous.db.utils.get_directory_path)),
                ('sale', models.PositiveSmallIntegerField(default=0)),
                ('delivery_period', models.PositiveSmallIntegerField()),
                ('delivery_cost', models.PositiveSmallIntegerField(default=0)),
                ('is_available', models.BooleanField(default=False)),
                ('product_status', models.CharField(choices=[('popular', 'Popular'), ('new', 'New'), ('recommend', 'Recommend'), ('sale', 'Sale')], default='new', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.subcategory')),
            ],
        ),
        migrations.CreateModel(
            name='RecommendProductProxy',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='store.product')),
            ],
            bases=('store.product',),
        ),
        migrations.CreateModel(
            name='SaleProductProxy',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='store.product')),
            ],
            bases=('store.product',),
        ),
        migrations.CreateModel(
            name='Variation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variation_category', models.CharField(choices=[('color', 'Color'), ('size', 'Size')], max_length=50)),
                ('variation_value', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=100)),
                ('rating', models.FloatField()),
                ('ip', models.CharField(blank=True, max_length=20)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NewProductProxy',
            fields=[
            ],
            options={
                'verbose_name': 'New Product',
                'verbose_name_plural': 'New Products',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('store.product',),
        ),
        migrations.CreateModel(
            name='PopularProductProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Popular Product',
                'verbose_name_plural': 'Popular Products',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('store.product',),
        ),
    ]
