services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=coupon_example'
      - 'MYSQL_ROOT_PASSWORD=1234'
    ports:
      - '3306:3306'
  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'
