spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    username: sa
    password:
    url: jdbc:h2:mem:chapter11
    driver-class-name: org.h2.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
