#spring:
#  datasource:
#    hikari:
#      jdbc-url: jdbc:mysql://localhost:3306/visitor
#      username: mysql
#      password: mysql
#      driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    properties:
#      hibernate:
#        hbm2ddl:
#          auto: create
