version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: 'core'
      MYSQL_ROOT_USER: 'root'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      TZ: Asia/Seoul
    ports:
      - "3306:3306"
    volumes:
      - ./init-script.sql:/docker-entrypoint-initdb.d/init-script.sql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci