spring:
  batch:
    jdbc:
      initialize-schema: always
  datasource:
    hikari:
      database-a:
        jdbc-url: jdbc:mysql://localhost:3306/spring-batch
        username: root
        password:
        driver-class-name: com.mysql.cj.jdbc.Driver
      database-b:
        jdbc-url: jdbc:mysql://localhost:3310/spring-batch
        username: root
        password:
        driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    open-in-view: true
