spring:
  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/test?useSSL=false&useUnicode=true&characterEncoding=UTF-8
      password: username
      username: password
      driver-class-name: com.mysql.cj.jdbc.Driver
