name: gradle build test with module

on:
  workflow_dispatch:

env:
  MYSQL_VERSION: '8.0'
  JAVA_VERSION: '17'
  DISTRIBUTION: 'temurin'

jobs:
  set-up:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/caching-docker-image
        with:
          MYSQL_VERSION: ${{ env.MYSQL_VERSION }}
  ktlint-check:
    needs: [set-up]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/ktlint-check
        with:
          JAVA_VERSION: ${{ env.JAVA_VERSION }}
          DISTRIBUTION: ${{ env.DISTRIBUTION }}
  run-test:
    needs: [set-up]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/run-test
        with:
          JAVA_VERSION: ${{ env.JAVA_VERSION }}
          DISTRIBUTION: ${{ env.DISTRIBUTION }}
  complete:
    needs: [run-test, ktlint-check]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci
      - uses: ./.github/workflows/echo
        with:
          MESSAGE: "hello world"
