# Generated by Django 3.2.4 on 2021-06-29 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
