### POST one-time-password 생성
POST {{base_url}}/one-time-password
Content-Type: application/json

{
  "phone": "01011112222"
}


### POST one-time-password 검증
POST {{base_url}}/one-time-password/verify
Content-Type: application/json

{
  "phone": "01011112222",
  "oneTimePassword": "908345"
}
