version: '3.8'

services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    restart: always
  database:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_DATABASE=visitor
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    ports:
      - '3306:3306'
