spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/houseUtils;
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: true
