### Path variable 유효성 검사
GET {{base-url}}/spring-validation/path-variable/15

### Request Params 유효성 검사
GET {{base-url}}/spring-validation/request-params?id=15

### Request Body 유효성 검사
POST {{base-url}}/spring-validation/request-body
Content-Type: application/json

{
  "id": 10,
  "message": "message"
}


