### Path variable 유효성 검사
GET {{base-url}}/validate/path-variable/15

### Request Params 유효성 검사
GET {{base-url}}/validate/request-params?id=0

### Request Body 유효성 검사
POST {{base-url}}/validate/request-body
Content-Type: application/json

{
  "id": 10,
  "message": "message"
}


