# Generated by Django 3.2.5 on 2021-07-09 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodrecipe',
            name='order',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
