name: run-test
author: bekurin
description: 'execute test'

inputs:
  JAVA_VERSION:
    description: 'java version (ex. 17, 21)'
    required: true
    default: '17'
  DISTRIBUTION:
    description: 'distribution'
    required: true
    default: 'temurin'

runs:
  using: composite
  steps:
    - uses: actions/cache@v4
      id: image-cache
      with:
        path: |
          ~/.docker
        key: docker-image-${{ runner.os }}
    - uses: actions/setup-java@v4
      with:
        java-version: ${{ inputs.JAVA_VERSION }}
        distribution: ${{ inputs.DISTRIBUTION }}
    - name: Grand execute permission for gradlew
      shell: bash
      run: chmod +x gradlew
    - name: Load cached docker images
      if: steps.image-cache.outputs.cache-hit == 'true'
      shell: bash
      run: |
        for file in ~/.docker/*.tar; do
          docker load -i "${file}"
        done
    - name: execute test
      shell: bash
      run: ./gradlew clean test --info
