name: trigger using pull request event

on:
  pull_request:
    types: [opened]

jobs:
  pull-request-job:
    runs-on: ubuntu-latest
    steps:
      - name: hello world
        run: echo hello world
