name: trigger using workflow dispatch event

on:
  workflow_dispatch:
    inputs:
      name:
        description: "set name"
        required: true
        default: "bekurin"
        type: string

jobs:
  push-job:
    runs-on: ubuntu-latest
    steps:
      - name: hello world
        run: echo hello ${{ inputs.name }}
