spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    username: sa
    password:
    url: jdbc:h2:mem:chapter18
    driver-class-name: org.h2.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/realms/master/protocol/openid-connect/certs
server:
  port: 9090