spring:
  datasource:
    hikari:
      jdbc-url: jdbc:mariadb://localhost:3306/jpa
      username: sa
      password: 1234
  jpa:
    properties:
      hibernate:
        show_sql: true
        hbm2ddl:
          auto: update
        format_sql: true
        physical_naming_strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
