spring:
  config:
    activate:
      on-profile: mariadb
  jpa:
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        hbm2ddl:
          auto: validate
      physical_naming_strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

logging:
  level:
    org:
      hibernate.SQL: debug
      springframework.orm.jpa: DEBUG
      springframework.transaction: DEBUG
