spring:
  jpa:
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        default_batch_fetch_size: 10000
      physical_naming_strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
  profiles:
    active: local



logging:
  level:
    org:
#      hibernate.SQL: trace
#      springframework.orm.jpa: DEBUG
#      springframework.transaction: DEBUG
