spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/batch
    username: sa
    password:
    driver-class-name: org.h2.Driver
  batch:
    jdbc:
      initialize-schema: always

  jpa:
    hibernate:
      ddl-auto: create

logging:
  level:
    org.hibernate.SQL: debug
